/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageResult
 */
export interface ImageResult {
    /**
     * 
     * @type {string}
     * @memberof ImageResult
     */
    base64: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResult
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof ImageResult
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof ImageResult
     */
    height: number;
}

/**
 * Check if a given object implements the ImageResult interface.
 */
export function instanceOfImageResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "base64" in value;
    isInstance = isInstance && "uuid" in value;
    isInstance = isInstance && "width" in value;
    isInstance = isInstance && "height" in value;

    return isInstance;
}

export function ImageResultFromJSON(json: any): ImageResult {
    return ImageResultFromJSONTyped(json, false);
}

export function ImageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'base64': json['base64'],
        'uuid': json['uuid'],
        'width': json['width'],
        'height': json['height'],
    };
}

export function ImageResultToJSON(value?: ImageResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'base64': value.base64,
        'uuid': value.uuid,
        'width': value.width,
        'height': value.height,
    };
}

